name: Run Clinic Reservation Bot

on:
  # This workflow is now only triggered by an external webhook call
  workflow_dispatch:

jobs:
  book-appointment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run reservation script
      run: python crawler.py
